version: '3.4'
services:
  app:
    image: wig-server
    build: ./
    depends_on:
      - db
    environment:
      MYSQL_DBNAME: wig
      MYSQL_USER: wig
      MYSQL_PASSWORD: wigsecret
      MYSQL_HOST: "db:3306"  
    ports:
      - "30001:30001"
    networks:
      - wig-db
        
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: wig
      MYSQL_USER: wig
      MYSQL_PASSWORD: wigsecret
    volumes:
      - wig-db:/var/lib/mysql
    networks:
      - wig-db

      
volumes:
  wig-db:

networks:
  wig-db:
    driver: overlay
