version: '3.4'
services:

        
  db:
    container_name: wigdb
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: wig
      MYSQL_USER: wig
      MYSQL_PASSWORD: wigsecret
    volumes:
    - wig-db:/var/lib/mysql
    ports:
      - "3306:3306"

      
volumes:
  wig-db:
