version: '3.4'
services:
  app:
    image: wig-server
    build: ./
    depends_on:
      - db
    ports:
      - "30001:30001"
    networks:
      - wig-db
        
  db:
    container_name: wigdb
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: wig
      MYSQL_USER: wig
      MYSQL_PASSWORD: wigsecret
    volumes:
    - wig-db:/var/lib/mysql
    ports:
      - "3306:3306"

      
volumes:
  wig-db:

  networks:
  wig-db:
    driver: overlay
