name: Test AWS Connection

on:
  push:
    branches:
      - dev

jobs:
  test-aws-connection:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.AWS_WIG }}

      - name: Test SSH Connection
        run: ssh -i $SSH_PRIVATE_KEY admin@ec2-34-201-123-65.compute-1.amazonaws.com echo "SSH successful"
