name: SSH Connection Test

on:
  push:
    branches:
      - dev

jobs:
  test-ssh-connection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test SSH Connection
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 34.201.123.65
          username: admin
          key: ${{ secrets.AWS_WIG }}
